const TRANSACTION_FEE = 1;

const INITIAL_BALANCE = 100;

const TRANSACTION_THRESHOLD = 3;

const VALIDATOR_FEE = 30;



module.exports = {
    TRANSACTION_FEE,
    INITIAL_BALANCE,
    TRANSACTION_THRESHOLD,
    VALIDATOR_FEE,
};